language: objective-c
osx_image: xcode8.2
script:
  - xcodebuild -scheme EGFormValidator -project EGFormValidator.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.0' build test
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'EGFormValidator'
